### ISSUE TITLE
How to make my own stubs?

### ISSUE THREAD

**Issue by AlekseiBalyshev** [gtalarico/ironpython-stubs#10]
Hello, could you please describe how to make my own stubs? 
I'd like to add Autodesk Navisworks, AutoCAD, Civil3D and a couple of other dll's. I use VS Code.

**Comment by gtalarico** [comment]
Give it shot with one of these you listed and we can go from there.

1. Clone this repository

2. Edit the `PATH` variable in [default_settings.py](https://github.com/gtalarico/ironpython-stubs/blob/master/ironstubs/default_settings.py) to include the location of the DLL you want to create a stub for.

3. From the root directory in this repository, run:
`ipy -m ironstubs make NameOfDllWithoutExtension`
(eg. `ipy -m ironstubs make RevitAPIUI`)

Let me know if that works

**Comment by mitevpi** [comment]
I gave it a shot with a custom class library, but got this error:

![image](https://user-images.githubusercontent.com/25568566/39370038-e069119c-4a0b-11e8-94ba-ab766f2bae48.png)

Is there something I need to do in my class library to be able to generate stubs, or is the stub generator just not made for custom code.

**Comment by gtalarico** [comment]
It should work for most dlls, but some have quirks. The main revit dlls for example only runs inside of revit.

The error you are getting above has to do with ironpython frames. 
Try running
`ipy - X:FullFrames -m... `

**Comment by cutmeat** [comment]
Hey,
I've been trying to generate some stubs for my Autostudio2019 Dynamo as well. Unfortunately I'm getting errors as well, probably related to my IronPython version (installed by the Autodesk installer):
![grafik](https://user-images.githubusercontent.com/31467653/45973787-b5c72500-c03f-11e8-90e2-be76400b43ec.png)
I looked at that Object.py, it didn't have the utf-8 thing in the header  and three strange characters in the file. I tried different encodings but couldn't find one that made sense, so tried out what would happen if I deleted the characters. I got new error messages:
![grafik](https://user-images.githubusercontent.com/31467653/45973909-08084600-c040-11e8-81fe-0a65005bc73d.png)
I reverted Object.py, seeing as the error is probably in my IronPython version itelfs somehow.
FYI:
![grafik](https://user-images.githubusercontent.com/31467653/45974007-5ddcee00-c040-11e8-8a4f-ac9a88093214.png)
Any idea on how to get this to work? I could try with another IronPython?

**Comment by gtalarico** [comment]
> is it alright to delete my comment?
Sure, feel free to delete it

**Comment by MrMontana1889** [comment]
I installed IronPython 3.4 alpha-1 (finally figured out the ipy is "IronPython"). since this version is compatible with Python 3.4+.  I tried running your command but I get this:
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files\IronPython 3.4\Lib\runpy.py", line 182, in run_module
  File ".\ironstubs\__main__.py", line 30, in <module>
  File "C:\Program Files\IronPython 3.4\Lib\runpy.py", line 95, in _run_module_code
  File "C:\Program Files\IronPython 3.4\Lib\runpy.py", line 85, in _run_code
ImportError: No module named 'utils.docopt'

Any ideas?  I'm trying to generate stubs for some custom C# DLLs.  In this case it is just one DLL..

Should I use the official release instead of the alpha version?
