### ISSUE TITLE
ImportError: No module named 'utils.docopt'

### ISSUE THREAD

**Issue by drache42** [gtalarico/ironpython-stubs#34]
I have ironpython installed, I can't get the ironpython-stub modules to work.

```python
❯ ipy -m ironstubs help
Unhandled exception:
Traceback (most recent call last):
  File "C:\Users\sfroehlich\.dotnet\tools\.store\ironpython.console\3.4.0\ironpython.console\3.4.0\tools\net6.0\any\lib\runpy.py", line 182, in run_module
  File ".\ironstubs\__main__.py", line 30, in <module>
  File "C:\Users\sfroehlich\.dotnet\tools\.store\ironpython.console\3.4.0\ironpython.console\3.4.0\tools\net6.0\any\lib\runpy.py", line 95, in _run_module_code
  File "C:\Users\sfroehlich\.dotnet\tools\.store\ironpython.console\3.4.0\ironpython.console\3.4.0\tools\net6.0\any\lib\runpy.py", line 85, in _run_code
ImportError: No module named 'utils.docopt'
```

From what I can tell, [this line](https://github.com/gtalarico/ironpython-stubs/blob/master/ironstubs/__main__.py#L30) is trying to pull a [module that is includes](https://github.com/gtalarico/ironpython-stubs/blob/master/ironstubs/utils/docopt.py).

**Comment by drache42** [comment]
I was using IronPython 3.4 instead of 2.7. 

Using 2.7 allowed me to at least get the `help` working
